/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    videos: Video;
    music: Music;
    users: User;
    socialmedia: Socialmedia;
    search: Search;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    music: MusicSelect<false> | MusicSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    socialmedia: SocialmediaSelect<false> | SocialmediaSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    home: Home;
    'theme-settings': ThemeSetting;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    'theme-settings': ThemeSettingsSelect<false> | ThemeSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Name to show in the menu of the webpage and also as part of the browser's tab text.
   */
  pageTitle: string;
  /**
   * Name of the web path to enter the page. For "shop-royalties" it would be accessed via "https://davidjbarrios.com/shop-royalties/". All in lowercase, no accents, use "-" instead of whitespace.Examples: "shop-royalties", "blog", "3d-animations".
   */
  pageName: string;
  /**
   * Either block based made up of a sequence of blocks like textWithVideo or textWithHtml or a video grid selected from the music or video collections.
   */
  pageType: 'blockPage' | 'videoGridPage';
  /**
   * Lower numbers appear first in the menu.
   */
  priority?: number | null;
  /**
   * Describe whats the page for. It's used for SEO optimization.
   */
  pageDescription: string;
  content?: {
    content?:
      | (
          | RichTextBlock
          | ImageBlock
          | TextWithImageBlock
          | TextWithVideo
          | MediaGridBlock
          | VideoBlock
          | HtmlBlock
          | TextWithHTML
        )[]
      | null;
  };
  /**
   * Select the videos to display.
   */
  mediaItems: (
    | {
        relationTo: 'videos';
        value: number | Video;
      }
    | {
        relationTo: 'music';
        value: number | Music;
      }
  )[];
  publishedAt?: string | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'richTextBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBlock".
 */
export interface ImageBlock {
  imageUrl: string;
  /**
   * Describe the image for screen readers and SEO.
   */
  altText: string;
  /**
   * If not specified the width will be that of the original image.
   */
  width?: number | null;
  /**
   * If not specified the height will be that of the original image.
   */
  height?: number | null;
  /**
   * Actual width and height are automatically detected and saved on publish.
   */
  imageDimensions?: {
    width?: number | null;
    height?: number | null;
  };
  /**
   * Choose how to align the image within the content column.
   */
  alignment?: ('left' | 'center' | 'right') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'imageBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "textWithImageBlock".
 */
export interface TextWithImageBlock {
  imageUrl: string;
  /**
   * Describe the image for screen readers and SEO.
   */
  altText: string;
  /**
   * Choose how to align the image relative to the text.
   */
  alignment?: ('left' | 'right') | null;
  /**
   * % of horizontal space that the text takes relative to the video.
   */
  horizontalTextSpace?: number | null;
  usePercentageBasedPadding?: boolean | null;
  imagePadding?: ('left' | 'center' | 'Right') | null;
  /**
   * % of empty margin space of the image to leave relative to the text.
   */
  percentageImagePadding?: number | null;
  /**
   * Actual width and height are automatically detected and saved on publish.
   */
  imageDimensions?: {
    width?: number | null;
    height?: number | null;
  };
  richText?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'textWithImageBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "textWithVideo".
 */
export interface TextWithVideo {
  videoUrl: string;
  /**
   * Choose how to align the video relative to the text.
   */
  videoAlignment?: ('left' | 'right') | null;
  /**
   * % of horizontal space that the text takes relative to the video.
   */
  horizontalTextSpace?: number | null;
  usePercentageBasedPadding?: boolean | null;
  videoPadding?: ('left' | 'center' | 'Right') | null;
  /**
   * % of empty margin space of the video to leave relative to the text.
   */
  percentageVideoPadding?: number | null;
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'textWithVideo';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaGridBlock".
 */
export interface MediaGridBlock {
  title?: string | null;
  /**
   * Select how many videos per row.
   */
  columns?: ('2' | '3' | '4') | null;
  /**
   * Select videos to display.
   */
  mediaItems: (
    | {
        relationTo: 'videos';
        value: number | Video;
      }
    | {
        relationTo: 'music';
        value: number | Music;
      }
  )[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: number;
  videoUrl: string;
  description?: string | null;
  /**
   * Lower numbers appear first. Leave blank to send to the end of the list.
   */
  priority?: number | null;
  useThumbnailUrl?: boolean | null;
  /**
   * Set a custom thumbnail URL. If disabled, youtube's thumbnail Url is used.
   */
  thumbnailUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "music".
 */
export interface Music {
  id: number;
  videoUrl: string;
  description?: string | null;
  /**
   * Lower numbers appear first. Leave blank to send to the end of the list.
   */
  priority?: number | null;
  useThumbnailUrl?: boolean | null;
  /**
   * Set a custom thumbnail URL. If disabled, youtube's thumbnail Url is used.
   */
  thumbnailUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoBlock".
 */
export interface VideoBlock {
  /**
   * e.g., https://www.youtube.com/watch?v=...
   */
  videoUrl: string;
  caption?: string | null;
  /**
   * Choose how to align the video within the content column.
   */
  alignment?: ('left' | 'center' | 'right') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'videoBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HtmlBlock".
 */
export interface HtmlBlock {
  /**
   * Paste a HTML snippet here. Be cautious as this will be rendered directly on the page.
   */
  htmlContent: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'htmlBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "textWithHTML".
 */
export interface TextWithHTML {
  /**
   * Paste a HTML snippet here. Be cautious as this will be embedded directly on the page.
   */
  htmlContent: string;
  /**
   * Choose how to align the html relative to the text.
   */
  htmlAlignment?: ('left' | 'right') | null;
  /**
   * % of horizontal space that the text takes relative to the video.
   */
  horizontalTextSpace?: number | null;
  usePercentageBasedPadding?: boolean | null;
  htmlPadding?: ('left' | 'center' | 'Right') | null;
  /**
   * % of empty margin space of the video to leave relative to the text.
   */
  percentageVideoPadding?: number | null;
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'textWithHTML';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role?: ('admin' | 'user') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "socialmedia".
 */
export interface Socialmedia {
  id: number;
  /**
   * Name to show up as the text that shows up when the mouse is on top of the icon.
   */
  name: string;
  /**
   * URL to go to when clicking the icon.
   */
  url: string;
  /**
   * URL of the image to be used as icon.
   */
  iconUrl: string;
  /**
   * To force a change in size of the image url used for the icon.
   */
  redimensionIcon?: boolean | null;
  /**
   * New width of the icon (in pixels).
   */
  redimensionWidth?: number | null;
  /**
   * New height of the icon.
   */
  redimensionHeight?: number | null;
  /**
   * Lower numbers appear first. Leave blank to send to the end of the list.
   */
  priority?: number | null;
  /**
   * Actual width and height are automatically detected and saved on publish.
   */
  imageDimensions?: {
    width?: number | null;
    height?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'pages';
    value: number | Page;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'videos';
        value: number | Video;
      } | null)
    | ({
        relationTo: 'music';
        value: number | Music;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'socialmedia';
        value: number | Socialmedia;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'payload-jobs';
        value: number | PayloadJob;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  pageTitle?: T;
  pageName?: T;
  pageType?: T;
  priority?: T;
  pageDescription?: T;
  content?:
    | T
    | {
        content?:
          | T
          | {
              richTextBlock?: T | RichTextBlockSelect<T>;
              imageBlock?: T | ImageBlockSelect<T>;
              textWithImageBlock?: T | TextWithImageBlockSelect<T>;
              textWithVideo?: T | TextWithVideoSelect<T>;
              mediaGrid?: T | MediaGridBlockSelect<T>;
              videoBlock?: T | VideoBlockSelect<T>;
              htmlBlock?: T | HtmlBlockSelect<T>;
              textWithHTML?: T | TextWithHTMLSelect<T>;
            };
      };
  mediaItems?: T;
  publishedAt?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  richText?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBlock_select".
 */
export interface ImageBlockSelect<T extends boolean = true> {
  imageUrl?: T;
  altText?: T;
  width?: T;
  height?: T;
  imageDimensions?:
    | T
    | {
        width?: T;
        height?: T;
      };
  alignment?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "textWithImageBlock_select".
 */
export interface TextWithImageBlockSelect<T extends boolean = true> {
  imageUrl?: T;
  altText?: T;
  alignment?: T;
  horizontalTextSpace?: T;
  usePercentageBasedPadding?: T;
  imagePadding?: T;
  percentageImagePadding?: T;
  imageDimensions?:
    | T
    | {
        width?: T;
        height?: T;
      };
  richText?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "textWithVideo_select".
 */
export interface TextWithVideoSelect<T extends boolean = true> {
  videoUrl?: T;
  videoAlignment?: T;
  horizontalTextSpace?: T;
  usePercentageBasedPadding?: T;
  videoPadding?: T;
  percentageVideoPadding?: T;
  description?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaGridBlock_select".
 */
export interface MediaGridBlockSelect<T extends boolean = true> {
  title?: T;
  columns?: T;
  mediaItems?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoBlock_select".
 */
export interface VideoBlockSelect<T extends boolean = true> {
  videoUrl?: T;
  caption?: T;
  alignment?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HtmlBlock_select".
 */
export interface HtmlBlockSelect<T extends boolean = true> {
  htmlContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "textWithHTML_select".
 */
export interface TextWithHTMLSelect<T extends boolean = true> {
  htmlContent?: T;
  htmlAlignment?: T;
  horizontalTextSpace?: T;
  usePercentageBasedPadding?: T;
  htmlPadding?: T;
  percentageVideoPadding?: T;
  description?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  videoUrl?: T;
  description?: T;
  priority?: T;
  useThumbnailUrl?: T;
  thumbnailUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "music_select".
 */
export interface MusicSelect<T extends boolean = true> {
  videoUrl?: T;
  description?: T;
  priority?: T;
  useThumbnailUrl?: T;
  thumbnailUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "socialmedia_select".
 */
export interface SocialmediaSelect<T extends boolean = true> {
  name?: T;
  url?: T;
  iconUrl?: T;
  redimensionIcon?: T;
  redimensionWidth?: T;
  redimensionHeight?: T;
  priority?: T;
  imageDimensions?:
    | T
    | {
        width?: T;
        height?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  content?:
    | (
        | RichTextBlock
        | ImageBlock
        | TextWithImageBlock
        | TextWithVideo
        | MediaGridBlock
        | VideoBlock
        | HtmlBlock
        | TextWithHTML
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme-settings".
 */
export interface ThemeSetting {
  id: number;
  /**
   * Text to add right after page specific title on the brower tab. Example: Home — David J. Barrios.
   */
  postfixText?: string | null;
  /**
   * Description of the home page. For SEO purposes.
   */
  homePageDescription: string;
  /**
   * Title for the card that appears when the site is linked in social media sites.
   */
  openGraphTitle: string;
  /**
   * Image that shows on the card that apperas when the site is linked in social media sites.
   */
  openGraphImageURL: string;
  /**
   * The main name displayed in the top left.
   */
  logoText?: string | null;
  /**
   * The text that appears next to or under the name.
   */
  subText?: string | null;
  /**
   * Character used to separate the main logo text and the subtext. Only shows up when in mid size screen. Ex: David J. Barrios ◆ Audiovisual producer.
   */
  separatorChar?: string | null;
  /**
   * When columns get smaller than this, they wrap to a new row. Note: only applies when screen size is at least medium size.
   */
  minColumnWidthPx?: number | null;
  /**
   * The space between each menu item. Note: only applies when screen size is at least medium size.
   */
  gap?: number | null;
  /**
   * Text to show in the menu for the home link (which is always first in the menu).
   */
  homePageTitle: string;
  /**
   * How much extra space is present under the social media icons.
   */
  bottomPadding?: number | null;
  content?:
    | (
        | RichTextBlock
        | ImageBlock
        | TextWithImageBlock
        | TextWithVideo
        | MediaGridBlock
        | VideoBlock
        | HtmlBlock
        | TextWithHTML
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  content?:
    | T
    | {
        richTextBlock?: T | RichTextBlockSelect<T>;
        imageBlock?: T | ImageBlockSelect<T>;
        textWithImageBlock?: T | TextWithImageBlockSelect<T>;
        textWithVideo?: T | TextWithVideoSelect<T>;
        mediaGrid?: T | MediaGridBlockSelect<T>;
        videoBlock?: T | VideoBlockSelect<T>;
        htmlBlock?: T | HtmlBlockSelect<T>;
        textWithHTML?: T | TextWithHTMLSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme-settings_select".
 */
export interface ThemeSettingsSelect<T extends boolean = true> {
  postfixText?: T;
  homePageDescription?: T;
  openGraphTitle?: T;
  openGraphImageURL?: T;
  logoText?: T;
  subText?: T;
  separatorChar?: T;
  minColumnWidthPx?: T;
  gap?: T;
  homePageTitle?: T;
  bottomPadding?: T;
  content?:
    | T
    | {
        richTextBlock?: T | RichTextBlockSelect<T>;
        imageBlock?: T | ImageBlockSelect<T>;
        textWithImageBlock?: T | TextWithImageBlockSelect<T>;
        textWithVideo?: T | TextWithVideoSelect<T>;
        mediaGrid?: T | MediaGridBlockSelect<T>;
        videoBlock?: T | VideoBlockSelect<T>;
        htmlBlock?: T | HtmlBlockSelect<T>;
        textWithHTML?: T | TextWithHTMLSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}